# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Build-win
      run: |
        go env -w GOOS=windows
        go env -w GOARCH=amd64
        go build -o dist/Win.exe -v .
        
    - name: Build-amd64-linux
      run: |
        go env -w GOOS=linux
        go env -w GOARCH=amd64
        go build -o dist/Linux_amd64 -v .

    - name: Build-arm64-linux
      run: |
        go env -w GOOS=linux
        go env -w GOARCH=arm64
        go build -o dist/Linux_arm64 -v .

    - name: Build-mipsle-OpenWRT
      run: |
        go env -w GOOS=linux
        go env -w GOARCH=mipsle
        go env -w GOMIPS=softfloat
        go build -o dist/OpenWRT_mipsle -v .

    - name: Tidy up Setting
      run: |
        mv setting.json dist/
        mv store.keyFile dist/
        
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.3.1
      with:
        name: CrackMM
        path: dist/